### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by LuffySmile** [dtrihinas/datachain#1]

**Comment by dtrihinas** [comment]
Hi @LuffySmile 

there are a lot of examples and tests to play with but as we are in the process of doing some new updates, I've added a new notebook with some queries and data management operations that you may find useful.

check out this notebook https://github.com/dtrihinas/datachain/blob/master/Notebooks/groupby.ipynb it creates a connection to bigchaindb (you can change this to hyperledger if you want), creates a participant (keyset), creates a data asset and then appends mutable data updates. Afterwards there is cumsum query extracted natively as a pandas dataframe and even a groupby query.

hope this helps.

you can also find more examples in our paper at MEDES 2019.
